UIRSHOP.WEB.BO/Pages/Categories/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UIRSHOP.BL.Models.Dtos.CategoryDtos;
using UIRSHOP.WEB.BO.Services;

namespace UIRSHOP.WEB.BO.Pages.Categories;

public class CreateModel : PageModel
{
    private readonly CategoryService _service;
    public CreateModel(CategoryService service) => _service = service;


    [BindProperty]
    public CategoryDto CategoryDto { get; set; }




    public async Task<IActionResult> OnPostCreate()
    {
        if (string.IsNullOrEmpty(CategoryDto.Name) || !ModelState.IsValid)
        {
            ModelState.AddModelError("CategoryDto.Name", "The field \"Name\" is required!");
            return Page();
        }
        CategoryDto.CreatedDate = DateTime.Now;
        await _service.Create(CategoryDto);
        return RedirectToPage("/Categories/Index");
    }
}

UIRSHOP.WEB.BO/Pages/Categories/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UIRSHOP.BL.Models.Dtos.CategoryDtos;
using UIRSHOP.WEB.BO.Services;

namespace UIRSHOP.WEB.BO.Pages.Categories;

public class DetailsModel : PageModel
{
    private readonly CategoryService _service;
    public DetailsModel(CategoryService service) => _service = service;



    [BindProperty]
    public CategoryDto CategoryDto { get; set; }




    public async Task OnGet(int id)
        => CategoryDto = await _service.Find(id);



    public async Task<IActionResult> OnPostUpdate()
    {
        if (string.IsNullOrEmpty(CategoryDto.Name) || !ModelState.IsValid)
        {
            ModelState.AddModelError("CategoryDto.Name", "The field \"Name\" is required!");
            return Page();
        }
        CategoryDto.UpdatedDate = DateTime.Now;
        await _service.Update(CategoryDto.Id, CategoryDto);
        return RedirectToPage("/Categories/Index");
    }


    public async Task<IActionResult> OnPostDelete()
    {
        await _service.Delete(CategoryDto.Id);
        return RedirectToPage("/Categories/Index");
    }
}

UIRSHOP.WEB.BO/Pages/Categories/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using UIRSHOP.BL.Models.Dtos.CategoryDtos;
using UIRSHOP.WEB.BO.Services;

namespace UIRSHOP.WEB.BO.Pages.Categories;

public class IndexModel : PageModel
{
    private readonly CategoryService _service;
    public IndexModel(CategoryService service) => _service = service;


    public IEnumerable<CategoryDto> CategoryDtos { get; set; }


    public async Task OnGet()
        => CategoryDtos = await _service.FindAll();
}

UIRSHOP.WEB.BO/Pages/Clients/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UIRSHOP.WEB.BO.Pages.Clients
{
    public class DetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

UIRSHOP.WEB.BO/Pages/Products/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UIRSHOP.BL.Models.Dtos.ProductDtos;
using UIRSHOP.BL.Models.Dtos.CategoryDtos;
using UIRSHOP.WEB.BO.Services;
using UIRSHOP.BL.Models.Dtos.SupplierDtos;

namespace UIRSHOP.WEB.BO.Pages.Products;

public class CreateModel : PageModel
{
    private readonly ProductService _serviceP;
    private readonly CategoryService _serviceC;
    private readonly SupplierService _serviceS;
    private readonly IWebHostEnvironment _env;
    public CreateModel(ProductService serviceP, CategoryService serviceC, SupplierService serviceS, IWebHostEnvironment env)
    {
        _serviceP = serviceP;
        _serviceC = serviceC;
        _serviceS = serviceS;
        _env = env;
    }


    [BindProperty]
    public ProductDto ProductDto { get; set; }
    public IEnumerable<CategoryDto> CategoryDtos { get; set; }
    public IEnumerable<SupplierDto> SupplierDtos { get; set; }

    public async Task OnGet()
    {
        CategoryDtos = await _serviceC.FindAll();
        SupplierDtos = await _serviceS.FindAll();
    }


    public async Task<IActionResult> OnPostCreate()
    {
        if (string.IsNullOrEmpty(ProductDto.Name) || !ModelState.IsValid)
        {
            ModelState.AddModelError("ProductDto.Name", "The field \"Name\" is required!");
            return Page();
        }
        ProductDto.ImagePath = await InsertImagesAsync();
        await _serviceP.Create(ProductDto);
        return RedirectToPage("/Products/Index");
    }




    private async Task<string> InsertImagesAsync()
    {
        string path = string.Empty;
        try
        {
            var file = HttpContext.Request.Form.Files[0];

            if (file != null)
            {
                var fileName = $"{Guid.NewGuid()}_{file.FileName}";
                var filePath = Path.Combine(_env.WebRootPath, "images", "products", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                    await file.CopyToAsync(stream);

                path = fileName;
            }
        }
        catch (Exception)
        {
            return null;
        }
        return path;
    }
}

UIRSHOP.WEB.BO/Pages/Products/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UIRSHOP.BL.Models.Dtos.ProductDtos;
using UIRSHOP.BL.Models.Dtos.CategoryDtos;
using UIRSHOP.WEB.BO.Services;
using UIRSHOP.BL.Models.Dtos.SupplierDtos;

namespace UIRSHOP.WEB.BO.Pages.Products;

public class DetailsModel : PageModel
{
    private readonly ProductService _serviceP;
    private readonly CategoryService _serviceC;
    private readonly SupplierService _serviceS;
    private readonly IWebHostEnvironment _env;
    public DetailsModel(ProductService serviceP, CategoryService serviceC, SupplierService serviceS, IWebHostEnvironment env)
    {
        _serviceP = serviceP;
        _serviceC = serviceC;
        _serviceS = serviceS;
        _env = env;
    }


    [BindProperty]
    public ProductDto ProductDto { get; set; }
    public IEnumerable<CategoryDto> CategoryDtos { get; set; }
    public IEnumerable<SupplierDto> SupplierDtos { get; set; }

    public async Task OnGet(int id)
    {
        ProductDto = await _serviceP.Find(id);
        CategoryDtos = await _serviceC.FindAll();
        SupplierDtos = await _serviceS.FindAll();
    }


    public async Task<IActionResult> OnPostUpdate()
    {
        if (string.IsNullOrEmpty(ProductDto.Name) || !ModelState.IsValid)
        {
            ModelState.AddModelError("ProductDto.Name", "The field \"Name\" is required!");
            return Page();
        }
        var imagePath = await InsertImagesAsync();
        ProductDto.ImagePath = imagePath ?? ProductDto.ImagePath;
        await _serviceP.Update(ProductDto.Id, ProductDto);
        return RedirectToPage("/Products/Index");
    }


    public async Task<IActionResult> OnPostDelete()
    {
        await _serviceP.Delete(ProductDto.Id);
        return RedirectToPage("/Products/Index");
    }




    private async Task<string> InsertImagesAsync()
    {
        string path = string.Empty;
        try
        {
            var file = HttpContext.Request.Form.Files[0];

            if (file != null)
            {
                var fileName = $"{Guid.NewGuid()}_{file.FileName}";
                var filePath = Path.Combine(_env.WebRootPath, "images", "products", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                    await file.CopyToAsync(stream);

                path = fileName;
            }
        }
        catch (Exception)
        {
            return null;
        }
        return path;
    }
}

UIRSHOP.WEB.BO/Pages/Stock/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UIRSHOP.WEB.BO.Pages.Stock
{
    public class DetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

UIRSHOP.WEB.BO/Pages/SubCategories/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UIRSHOP.BL.Models.Dtos.SubCategory;
using UIRSHOP.BL.Models.Dtos.CategoryDtos;
using UIRSHOP.WEB.BO.Services;

namespace UIRSHOP.WEB.BO.Pages.SubCategories;

public class CreateModel : PageModel
{
    private readonly SubCategoryService _service;
    private readonly CategoryService _categoryService;
    public CreateModel(SubCategoryService service, CategoryService categoryService)
    {
        _service = service;
        _categoryService = categoryService;
    }


    [BindProperty]
    public SubCategoryDto SubCategoryDto { get; set; }

    public IEnumerable<CategoryDto> CategoryDtos { get; set; }

    public async Task OnGet()
        => CategoryDtos = await _categoryService.FindAll();




    public async Task<IActionResult> OnPostCreate()
    {
        if (string.IsNullOrEmpty(SubCategoryDto.Name) || !ModelState.IsValid)
        {
            ModelState.AddModelError("SubCategoryDto.Name", "The field \"Name\" is required!");
            return Page();
        }
        SubCategoryDto.CreatedDate = DateTime.Now;
        await _service.Create(SubCategoryDto);
        return RedirectToPage("/SubCategories/Index");
    }
}

UIRSHOP.WEB.BO/Pages/SubCategories/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UIRSHOP.WEB.BO.Pages.SubCategories
{
    public class DetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

UIRSHOP.WEB.BO/Pages/Suppliers/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using UIRSHOP.BL.Models.Dtos.SupplierDtos;
using UIRSHOP.WEB.BO.Services;

namespace UIRSHOP.WEB.BO.Pages.Suppliers;

public class CreateModel : PageModel
{
    private readonly SupplierService _service;
    private readonly IWebHostEnvironment _env;
    public CreateModel(SupplierService service, IWebHostEnvironment env)
    {
        _service = service;
        _env = env;
    }


    [BindProperty]
    public SupplierDto SupplierDto { get; set; }




    public async Task<IActionResult> OnPostCreate()
    {
        SupplierDto.ImagePath = await InsertImagesAsync();
        if (string.IsNullOrEmpty(SupplierDto.Name) || !ModelState.IsValid)
        {
            ModelState.AddModelError("SupplierDto.Name", "The field \"Name\" is required!");
            return Page();
        }

        await _service.Create(SupplierDto);
        return RedirectToPage("/Suppliers/Index");
    }




    private async Task<string> InsertImagesAsync()
    {
        string path = string.Empty;
        try
        {
            var file = HttpContext.Request.Form.Files[0];

            if (file != null)
            {
                var fileName = $"{Guid.NewGuid()}_{file.FileName}";
                var filePath = Path.Combine(_env.WebRootPath, "images", "suppliers", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                    await file.CopyToAsync(stream);

                path = fileName;
            }
        }
        catch (Exception)
        {
            return null;
        }
        return path;
    }
}

UIRSHOP.WEB.BO/Pages/Suppliers/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UIRSHOP.BL.Models.Dtos.SupplierDtos;
using UIRSHOP.DAL;
using UIRSHOP.WEB.BO.Services;

namespace UIRSHOP.WEB.BO.Pages.Suppliers;

public class DetailsModel : PageModel
{
    private readonly SupplierService _service;
    private readonly IWebHostEnvironment _env;

    public DetailsModel(SupplierService service, IWebHostEnvironment env)
    {
        _service = service;
        _env = env;
    }

    [BindProperty]
    public SupplierDto SupplierDto { get; set; }



    public async Task OnGet(int id)
        => SupplierDto = await _service.Find(id);


    public async Task<IActionResult> OnPostUpdate()
    {
        if (string.IsNullOrEmpty(SupplierDto.Name) || !ModelState.IsValid)
        {
            ModelState.AddModelError("SupplierDto.Name", "The field \"Name\" is required!");
            return Page();
        }
        var imagePath = await InsertImagesAsync();
        SupplierDto.ImagePath = imagePath ?? SupplierDto.ImagePath;
        await _service.Update(SupplierDto.Id, SupplierDto);
        return RedirectToPage("/Suppliers/Index");
    }


    public async Task<IActionResult> OnPostDelete()
    {
        await _service.Delete(SupplierDto.Id);
        return RedirectToPage("/Suppliers/Index");
    }



    private async Task<string> InsertImagesAsync()
    {
        string path = string.Empty;
        try
        {
            var file = HttpContext.Request.Form.Files[0];

            if (file != null)
            {
                var fileName = $"{Guid.NewGuid()}_{file.FileName}";
                var filePath = Path.Combine(_env.WebRootPath, "images", "suppliers", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                    await file.CopyToAsync(stream);

                path = fileName;
            }
        }
        catch (Exception)
        {
            return null;
        }
        return path;
    }
}

UIRSHOP.WEB.BO/Pages/Categories/Create.cshtml
@page
@model UIRSHOP.WEB.BO.Pages.Categories.CreateModel
@{
    ViewData["Title"] = "New Category";
}


<div class="container">

    <div class="row justify-content-center mb-3">
        <div class="col-12">
            <div class="card mx-auto">
                <div class="card-body text-center">
                    <h2>New Category</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card mx-auto">
                <div class="card-body">
                    <p class="card-description text-primary">
                        Fill the following fields
                    </p>
                    <form method="post" class="forms-sample">

                        <div class="form-group row">
                            <span asp-validation-for="CategoryDto.Name" class="text text-danger"></span>
                            <label asp-for="CategoryDto.Name" class="col-sm-3 col-form-label">Name</label>
                            <div class="col-sm-9">
                                <input asp-for="CategoryDto.Name" type="text" class="form-control" placeholder="enter category's name">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="CategoryDto.Description" class="col-sm-3 col-form-label">Description</label>
                            <div class="col-sm-9">
                                <textarea asp-for="CategoryDto.Description" class="form-control" rows="6" placeholder="type description"></textarea>
                            </div>
                        </div>

                        <button asp-page-handler="Create" class="btn btn-primary mr-2">Add</button>
                        <button type="reset" class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

UIRSHOP.WEB.BO/Pages/Categories/Details.cshtml
@page
@model UIRSHOP.WEB.BO.Pages.Categories.DetailsModel
@{
    ViewData["Title"] = "Category Details";
}


<div class="container">

    <div class="row justify-content-center mb-3">
        <div class="col-12">
            <div class="card mx-auto">
                <div class="card-body text-center">
                    <h2>Category Details</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card mx-auto">
                <div class="card-body">
                    <p class="h6 card-description text-primary">
                        Edit category details
                    </p>
                    <form method="post" class="forms-sample">

                        <div class="form-group row">
                            <span asp-validation-for="CategoryDto.Name" class="text text-danger"></span>
                            <label asp-for="CategoryDto.Name" class="col-sm-3 col-form-label">Name</label>
                            <div class="col-sm-9">
                                <input asp-for="CategoryDto.Name" type="text" class="form-control" placeholder="enter category's name">
                            </div>
                        </div>

                        <div class="form-group row">
                            <span asp-validation-for="CategoryDto.Description" class="text text-danger"></span>
                            <label asp-for="CategoryDto.Description" class="col-sm-3 col-form-label">Description</label>
                            <div class="col-sm-9">
                                <textarea asp-for="CategoryDto.Description" class="form-control" rows="6" placeholder="type description"></textarea>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="CategoryDto.CreatedDate" class="col-sm-3 col-form-label">Creation Date</label>
                            <div class="col-sm-9">
                                <input asp-for="CategoryDto.CreatedDate" type="datetime" class="form-control" readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label asp-for="CategoryDto.UpdatedDate" class="col-sm-3 col-form-label">Update Date</label>
                            <div class="col-sm-9">
                                <input asp-for="CategoryDto.UpdatedDate" type="datetime" class="form-control" readonly>
                            </div>
                        </div>

                        <button asp-page-handler="Update" class="btn btn-info mr-2">Update</button>
                        <button asp-page-handler="Delete" class="btn btn-danger mr-2">Delete</button>
                        <a asp-page="/Categories/Index" class="btn btn-secondary">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

UIRSHOP.WEB.BO/Pages/Categories/Index.cshtml
@page
@model UIRSHOP.WEB.BO.Pages.Categories.IndexModel
@{
    ViewData["Title"] = "Manage Categories";
}


<div class="container">
    <div class="row justify-content-center mb-3">
        <div class="col-12">
            <div class="card mx-auto">
                <div class="card-body text-center">
                    <h2>Categories</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th><span class="h4">Name</span></th>
                                    <th><span class="h4">Description</span></th>
                                    <th><span class="h4">Creation Date</span></th>
                                    <th><span class="h4">Update date</span></th>
                                    <th class="text-center"><span class="h4">Action</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.CategoryDtos)
                                {
                                    <tr>
                                        <td><span class="h4">@item.Name</span></td>
                                        <td><span class="h4">@item.Description</span></td>
                                        <td><span class="h4">@item.CreatedDate</span></td>
                                        <td><span class="h4">@item.UpdatedDate</span></td>
                                        <td class="text-center"><a asp-route-id="@item.Id" asp-page="/Categories/Details" class="btn btn-info"><span class="h5">Manage</span></a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>